### ISSUE TITLE
Add feature toggles

### ISSUE THREAD

**Issue by madeleineostoja** [jonathantneal/oldie#1]
Would be great to be able to toggle features on/off at initialisation, similar to how [Rucksack](https://github.com/simplaio/rucksack) and others do things. This is especially important if you just want to add fallbacks in your main css, and therefore turn off destructive transforms like killing media queries.

**Comment by jonathantneal** [comment]
You can disable any plugin using options https://github.com/jonathantneal/oldie#options

Is this what you were looking for?

**Comment by madeleineostoja** [comment]
Ah sorry, missed that!
